### ISSUE TITLE
מציאת מסלול

### ISSUE THREAD

**Issue by erelsgl** [DanielAbergel/BFS-Unity#1]
יפה מאד, אבל אם תרצה להשתמש בזה במשחק,
תצטרך לא רק פונקציה שאומרת אם יש מסלול,
אלא גם פונקציה שמוצאת את המסלול עצמו

**Comment by DanielAbergel** [comment]
אני אוסיף פונקציונליות שמחזירה את המסלול 
תודה 

נשלח מה-iPhone שלי

**Comment by DanielAbergel** [comment]
הוספתי פוקצייה למציאת המסלול עצמו .

**Comment by DanielAbergel** [comment]
a98d862216d08eedf1101b56dd075386daab7ec2
הקומיט של השינויים שבוצעו
